language: node_js
os:
  - osx
  - linux
node_js: 8

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 5;
    fi

install:
  - npm ci
  - cd server && npm ci
  - cd ..

script:
  - npm test

after_success:
  - cd server && npm run coverage && cd ..

cache: npm
